// Copies the design-token blocks (CSS custom properties + theme variants) from the tenant web app's
// styles.scss into a generated partial here, so both apps share ONE source of truth for colors, radii,
// shadows, etc. — without a fragile symlink or hand-duplicated palette. Run on prebuild/prestart/prelint.
//
// It extracts three brace-balanced top-level blocks by selector:
//   :root, [data-theme="dark"] { … }
//   @media (prefers-color-scheme: light) { … }
//   [data-theme="light"] { … }
// If the tenant file is restructured, this fails loudly rather than silently emitting stale tokens.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const source = join(here, "../../web/src/styles.scss");
const target = join(here, "../src/tokens.generated.scss");

const css = readFileSync(source, "utf8");

// Extract the brace-balanced block that begins at the first occurrence of `marker`.
function extractBlock(marker) {
  const start = css.indexOf(marker);
  if (start === -1) throw new Error(`sync-styles: could not find token block starting with: ${marker}`);
  const open = css.indexOf("{", start);
  if (open === -1) throw new Error(`sync-styles: no opening brace after: ${marker}`);
  let depth = 0;
  for (let i = open; i < css.length; i++) {
    if (css[i] === "{") depth++;
    else if (css[i] === "}") {
      depth--;
      if (depth === 0) return css.slice(start, i + 1);
    }
  }
  throw new Error(`sync-styles: unbalanced braces for block: ${marker}`);
}

const blocks = [
  extractBlock(":root,"),
  extractBlock("@media (prefers-color-scheme: light)"),
  extractBlock('[data-theme="light"]'),
];

const banner = "// GENERATED by scripts/sync-styles.mjs from apps/web/src/styles.scss — do not edit by hand.\n\n";
writeFileSync(target, banner + blocks.join("\n\n") + "\n");
console.log(`sync-styles: wrote ${target}`);
