export const GENERAL_NAME_MAX_LENGTH = 120;
export const WORKSPACE_ENTITY_NAME_MAX_LENGTH = 35;
export const CARD_LABEL_NAME_MAX_LENGTH = 25;
export const CUSTOM_FIELD_OPTION_LABEL_MAX_LENGTH = GENERAL_NAME_MAX_LENGTH;
