import { ChangeDetectionStrategy, Component, type OnInit, inject, signal } from "@angular/core";
import type { AdminAccountListItem } from "@kanera/shared/dto";
import { ApiClient } from "../../core/api/api.client";
import { AdminAuthService } from "../../core/auth/admin-auth.service";
import { ConfirmService } from "../../shared/confirm.service";
import { TableControlsComponent, TablePagerComponent } from "../../shared/table-controls.component";
import { ToastService } from "../../shared/toast.service";

@Component({ selector: "a-admins-page", standalone: true, imports: [TableControlsComponent, TablePagerComponent], changeDetection: ChangeDetectionStrategy.OnPush, template: `
<header class="page-head"><div><h1>Administrators</h1><p class="muted">Manage platform-wide superadmin access.</p></div></header>
<section class="card invite"><h2>Invite a superadmin</h2><div class="form-row"><input class="input" placeholder="Display name" [value]="displayName()" (input)="displayName.set($any($event.target).value)"/><input class="input" type="email" placeholder="Email address" [value]="email()" (input)="email.set($any($event.target).value)"/><button class="btn btn-primary" type="button" [disabled]="busy()||!displayName().trim()||!email().trim()" (click)="invite()">Send invite</button></div></section>
<a-table-controls [query]="query()" placeholder="Search administrators…" [page]="page()" [pageSize]="pageSize()" [total]="total()" [loading]="loading()" (queryChange)="onSearch($event)" (pageChange)="go($event)" (pageSizeChange)="resize($event)"/>
@if(loading()){<p class="muted">Loading…</p>}@else{<div class="table-wrap"><table class="data"><thead><tr>@for(c of columns;track c.key){<th><button class="sort" (click)="orderBy(c.key)">{{c.label}} {{arrow(c.key)}}</button></th>}<th></th></tr></thead><tbody>@for(item of items();track item.id){<tr><td>{{item.displayName}}</td><td class="muted">{{item.email}}</td><td><span class="badge" [class.badge-danger]="item.status==='disabled'">{{item.status}}</span></td><td class="muted">{{format(item.createdAt)}}</td><td class="muted">{{item.kind==='invite'?'Expires '+format(item.expiresAt!):(item.lastLoginAt?format(item.lastLoginAt):'Never')}}</td><td class="actions">@if(item.kind==='invite'){<button class="btn btn-sm" [disabled]="busy()" (click)="resend(item)">Resend</button><button class="btn btn-sm btn-danger" [disabled]="busy()" (click)="revoke(item)">Revoke</button>}@else if(item.status==='disabled'){<button class="btn btn-sm" [disabled]="busy()" (click)="enable(item)">Re-enable</button>}@else{<button class="btn btn-sm btn-danger" [disabled]="busy()||item.id===auth.user()?.id||activeCount()<=1" (click)="disable(item)">Disable</button>}</td></tr>}@empty{<tr><td colspan="6" class="muted">No administrators found.</td></tr>}</tbody></table></div><a-table-pager [page]="page()" [pageSize]="pageSize()" [total]="total()" [loading]="loading()" (pageChange)="go($event)" (pageSizeChange)="resize($event)" />}
`, styles: [`.page-head{margin-bottom:18px}.page-head h1{font-size:20px;margin:0 0 4px}.page-head p{margin:0}.invite{padding:16px;margin-bottom:20px}.invite h2{font-size:14px;margin:0 0 12px}.form-row{display:flex;gap:10px}.form-row .input{max-width:280px}.actions{display:flex;justify-content:flex-end;gap:6px;white-space:nowrap}.table-wrap{overflow-x:auto}.sort{border:0;background:none;padding:0;font:inherit;font-weight:inherit;color:inherit;cursor:pointer}`] })
export class AdminsPage implements OnInit {
  private readonly api=inject(ApiClient); private readonly toast=inject(ToastService); private readonly confirm=inject(ConfirmService); readonly auth=inject(AdminAuthService);
  readonly columns=[{key:"displayName",label:"Name"},{key:"email",label:"Email"},{key:"status",label:"Status"},{key:"createdAt",label:"Created"},{key:"lastActivityAt",label:"Last login / Expiry"}];
  readonly items=signal<AdminAccountListItem[]>([]); readonly total=signal(0); readonly page=signal(1); readonly pageSize=signal(25); readonly query=signal(""); readonly sort=signal("createdAt"); readonly direction=signal<"asc"|"desc">("desc"); readonly loading=signal(true); readonly busy=signal(false); readonly displayName=signal(""); readonly email=signal(""); private timer:ReturnType<typeof setTimeout>|null=null;
  readonly activeCount=()=>this.items().filter(i=>i.kind==="account"&&i.status==="active").length; readonly format=(v:string)=>new Date(v).toLocaleString();
  async ngOnInit(){await this.load()} onSearch(v:string){this.query.set(v);if(this.timer)clearTimeout(this.timer);this.timer=setTimeout(()=>{this.page.set(1);void this.load()},250)} go(p:number){this.page.set(p);void this.load()} resize(s:number){this.pageSize.set(s);this.page.set(1);void this.load()} orderBy(s:string){if(this.sort()===s)this.direction.update(d=>d==="asc"?"desc":"asc");else{this.sort.set(s);this.direction.set("asc")}this.page.set(1);void this.load()} arrow(s:string){return this.sort()===s?(this.direction()==="asc"?"↑":"↓"):""}
  async invite(){await this.run(async()=>{await this.api.post("/admin/admins/invites",{displayName:this.displayName().trim(),email:this.email().trim()});this.displayName.set("");this.email.set("")},"Invitation sent")} async resend(i:AdminAccountListItem){await this.run(()=>this.api.post(`/admin/admins/invites/${i.id}/resend`),"Invitation resent")} async revoke(i:AdminAccountListItem){if(await this.confirm.open({title:"Revoke invitation?",message:`The invitation for ${i.email} will no longer be usable.`,confirmLabel:"Revoke"}))await this.run(()=>this.api.delete(`/admin/admins/invites/${i.id}`),"Invitation revoked")} async disable(i:AdminAccountListItem){if(await this.confirm.open({title:`Disable ${i.displayName}?`,message:"Their active sessions will be revoked.",confirmLabel:"Disable"}))await this.run(()=>this.api.post(`/admin/admins/${i.id}/disable`),"Administrator disabled")} async enable(i:AdminAccountListItem){await this.run(()=>this.api.post(`/admin/admins/${i.id}/enable`),"Administrator re-enabled")}
  private async run(action:()=>Promise<unknown>,message:string){this.busy.set(true);try{await action();this.toast.success(message);await this.load()}catch(e){this.toast.error(e instanceof Error?e.message:"Action failed")}finally{this.busy.set(false)}}
  private async load():Promise<void>{this.loading.set(true);try{const p=new URLSearchParams({page:String(this.page()),pageSize:String(this.pageSize()),sort:this.sort(),direction:this.direction()});if(this.query().trim())p.set("q",this.query().trim());const r=await this.api.get<{items:AdminAccountListItem[];total:number}>(`/admin/admins?${p}`);if(!r.items.length&&r.total&&this.page()>1){this.page.update(v=>v-1);await this.load();return}this.items.set(r.items);this.total.set(r.total)}finally{this.loading.set(false)}}
}
